### ISSUE TITLE
Código de rastreio não aparece em telas pequenas 

### ISSUE THREAD

**Issue by luizbills** [claudiosanches/woocommerce-correios#244]
A seguinte regra no CSS do woocommerce impede que o código de rastreio apareça em telas menores: 

```css
table.shop_table_responsive tbody th {
  display: none;
}
```

![2023-01-19_08-48](https://user-images.githubusercontent.com/1798830/213434870-24e66651-ae8d-417a-bd88-4aca63ad9a2b.png)

![2023-01-19_08-51](https://user-images.githubusercontent.com/1798830/213435339-d76cb30b-727a-45ad-bd49-763982ef1458.png)
